name: liveness_rtmp
description: Liveness application

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_with_rtmp:
    path: ./rtmppublisher

  path_provider: ^1.6.8
  cupertino_icons: ^0.1.3
  video_player: ^0.10.11
  e2e: ^0.4.2
  wakelock: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
###  camera_with_rtmp:
###    path: ./rtmppublisher

flutter:
  uses-material-design: true